config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  get '/about' => 'pages#about'
  root 'pages#home'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
   def new
       @contact = Contact.new
   end
   
   def create
   end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/new.html.erb
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="well">
            <%= form_for @contact do |f| %>
            
            <div class="form-group">
                <%= f.label :name  %>
                <%= f.text_field :name, class: 'form-control'  %>
               </div>
                 <div class="form-group"> 
                 <%= f.label :email  %>
                <%= f.email_field :email, class: 'form-control'  %>
            </div> 
             <div class="form-group"> 
              <%= f.label :comments  %>
              <%= f.text_area :comments, class: 'form-control'  %>
            </div> 
             <%= f.submit 'Submit', class: 'btn btn-default'  %>
           <% end %>
       </div>
   </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Huene: The Art of Art Discovery</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!--<nav class-"navbar navbar-default navbar-static-top" role="navigation">-->
<!--  <div class='container'>-->
<!--    <div class="navbar-header">-->
<!--      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">-->
<!--        <span class="sr-only">Toggle naviagtion</span>-->
<!--        <span class="icon-bar"></span>-->
<!--        <span class="icon-bar"></span>-->
<!--        <span class="icon-bar"></span>-->
        
<!--      </button>-->
<!--     <%= link_to 'SaaS', root_path, class: 'navbar-brand' %>-->
<!--    </div>-->
    
<!--    <div class="collapse navbar-collapse" id="main-nav-collapse">-->
<!--      <ul class="nav navbar-new navbar-right">-->
<!--        <li><%= link_to "About", "#" %></li>-->
<!--      </ul>-->
      
      
<!--    </div>-->
<!--  </div>-->
<!--</nav>-->



<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class:'navbar-brand' do %>
      <i class="fa fa-users "></i>
     Huene
     <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="About">About</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to 'About Us', about_path %></li>
           <li> <%= link_to 'Contact', new_contact_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h2>About Us</h2>

app/views/pages/home.html.erb
<div class="jumbotron text-center">
<h1>Huene</h1>
<h3>Huene is a seven part story-driven audio course that teaches you how to find life-changing art by utilizing the vein-like patterns and mathematical structure of the universe as a blueprint for efficient art-discovery. </h3>
</div>